import argparse
import pickle

from load_data import Data
import random

parser = argparse.ArgumentParser()
parser.add_argument('--epochs', default=500, help='Number of epochs (default: 200)')
parser.add_argument('--batchsize', type=int, default=256, help='Batch size (default: 128)')
parser.add_argument('--num_filters', type=int, default=40, help='number of filters CNN')
parser.add_argument('--filt_h', type=int, default=1, help='filt_h of  CNN')
parser.add_argument('--filt_w', type=int, default=2, help='filt_w of CNN')
parser.add_argument('--conv_stride', type=int, default=2, help='stride of CNN')
parser.add_argument('--pool_h', type=int, default=1, help='pool_h')
parser.add_argument('--pool_w', type=int, default=2, help='pool_w')
parser.add_argument('--pool_stride', type=int, default=2, help='pool_w')
parser.add_argument('--learningrate', default=0.00055, help='Learning rate (default: 0.00005)')
parser.add_argument("--droupt_output_decoder", default=0.4, type=float, help="droupt regularization item 0.2")
parser.add_argument("--label_smoothing_decoder", default=0.1, type=float, help="label smoothing")
parser.add_argument("--CUDA", default=True, type=bool, help="True:GPU False:CPU")
parser.add_argument("--decoder_model_name", default='CE2T', type=str, help="CE2T ConnectE ETE")
parser.add_argument("--margin", default=2.0, type=float, help="ConnectE ETE’s margine ")
# embedding
parser.add_argument('--embsize_entity', default=100, help='Entity Embedding size (default: 200)')
parser.add_argument('--embsize_relation', default=100, help='Entity Embedding size (default: 200)')
parser.add_argument('--embsize_entity_type', default=200, help='Entity Type Embedding size (default: 100)')
# frgat
parser.add_argument('--num_layers', type=int, default=1, help='Number of FRGAT layers')
parser.add_argument('--nb_heads', type=int, default=1, help='Number of head attentions.')
parser.add_argument('--hidden_embedding_size', type=int, default=200, help='Number of hidden units.')
parser.add_argument('--output_embedding_size', type=int, default=600, help='Number of input units.')
parser.add_argument("--alpha", "--alpha", type=float, default=0.2, help="LeakyRelu alphs for FRGAT layer")
parser.add_argument('--frgat_drop', default=0.3, type=float, help='FRGAT dropout')
parser.add_argument('--frgat_output_dropout', default=0.2, type=float, help='FRGAT output dropout')
parser.add_argument('--frgat_initial_dropout', default=0.0, type=float, help='FRGAT initial dropout')
parser.add_argument('--frgat_computing_model', default='DisMult', type=str,
                    help='Attention computing model:TransE TransH TransD DisMult RotatE QuatE dot')
parser.add_argument('--frgat_composition_operator', default='mult', type=str, help='sub mult corr void')
# datapath
parser.add_argument('--indir', type=str, default='data/YAGO/',
                    help='Input dir of train, test and valid data: data/FB15K/ data/YAGO/ data/FB15K-237 data/JF17K')
parser.add_argument('--outdir', type=str, default='output/YAGO/', help='Output dir of model')
#load
parser.add_argument('--load', default='True',
                    help='If true, it loads a saved model in outdir and train or evaluate it (default: False)')
args = parser.parse_args()

d = Data(data_dir=args.indir)


#YAGO
# parser = argparse.ArgumentParser()
# parser.add_argument('--epochs', default=500, help='Number of epochs (default: 200)')
# parser.add_argument('--batchsize', type=int, default=256, help='Batch size (default: 128)')
# parser.add_argument('--num_filters', type=int, default=64, help='number of filters CNN')
# parser.add_argument('--filt_h', type=int, default=1, help='filt_h of  CNN')
# parser.add_argument('--filt_w', type=int, default=2, help='filt_w of CNN')
# parser.add_argument('--conv_stride', type=int, default=2, help='stride of CNN')
# parser.add_argument('--pool_h', type=int, default=1, help='pool_h')
# parser.add_argument('--pool_w', type=int, default=2, help='pool_w')
# parser.add_argument('--pool_stride', type=int, default=2, help='pool_w')
# parser.add_argument('--learningrate', default=0.00055, help='Learning rate (default: 0.00005)')
# parser.add_argument("--droupt_output_decoder", default=0.4, type=float, help="droupt regularization item 0.2")
# parser.add_argument("--label_smoothing_decoder", default=0.1, type=float, help="label smoothing")
# parser.add_argument("--CUDA", default=True, type=bool, help="True:GPU False:CPU")
# parser.add_argument("--decoder_model_name", default='CE2T', type=str, help="CE2T ConnectE ETE")
# parser.add_argument("--margin", default=2.0, type=float, help="ConnectE ETE’s margine ")
# parser.add_argument('--embsize_entity', default=100, help='Entity Embedding size (default: 200)')
# parser.add_argument('--embsize_relation', default=100, help='Entity Embedding size (default: 200)')
# parser.add_argument('--embsize_entity_type', default=200, help='Entity Type Embedding size (default: 100)')
# parser.add_argument('--num_layers', type=int, default=1, help='Number of FRGAT layers')
# parser.add_argument('--nb_heads', type=int, default=1, help='Number of head attentions.')
# parser.add_argument('--hidden_embedding_size', type=int, default=200, help='Number of hidden units.')
# parser.add_argument('--output_embedding_size', type=int, default=600, help='Number of input units.')
# parser.add_argument("--alpha", "--alpha", type=float, default=0.2, help="LeakyRelu alphs for FRGAT layer")
# parser.add_argument('--frgat_drop', default=0.3, type=float, help='FRGAT dropout')
# parser.add_argument('--frgat_output_dropout', default=0.2, type=float, help='FRGAT output dropout')
# parser.add_argument('--frgat_initial_dropout', default=0.0, type=float, help='FRGAT initial dropout')
# parser.add_argument('--frgat_computing_model', default='DisMult', type=str,
#                     help='Attention computing model:TransE TransH TransD DisMult RotatE QuatE dot')
# parser.add_argument('--frgat_composition_operator', default='mult', type=str, help='sub mult corr void')
# parser.add_argument('--indir', type=str, default='data/YAGO/',
#                     help='Input dir of train, test and valid data: data/FB15K/ data/YAGO/ data/FB15K-237 data/JF17K')
# parser.add_argument('--outdir', type=str, default='output/YAGO/', help='Output dir of model')

#FB15K
# parser = argparse.ArgumentParser()
# parser.add_argument('--epochs', default=500, help='Number of epochs (default: 200)')
# parser.add_argument('--batchsize', type=int, default=128, help='Batch size (default: 128)')
# parser.add_argument('--num_filters', type=int, default=64, help='number of filters CNN')
# parser.add_argument('--filt_h', type=int, default=1, help='filt_h of  CNN')
# parser.add_argument('--filt_w', type=int, default=2, help='filt_w of CNN')
# parser.add_argument('--conv_stride', type=int, default=2, help='stride of CNN')
# parser.add_argument('--pool_h', type=int, default=1, help='pool_h')
# parser.add_argument('--pool_w', type=int, default=2, help='pool_w')
# parser.add_argument('--pool_stride', type=int, default=2, help='pool_w')
# parser.add_argument('--learningrate', default=0.0001, help='Learning rate (default: 0.00005)')
# parser.add_argument("--droupt_output_decoder", default=0.4, type=float, help="droupt regularization item 0.2")
# parser.add_argument("--label_smoothing_decoder", default=0.1, type=float, help="label smoothing")
# parser.add_argument("--CUDA", default=True, type=bool, help="True:GPU False:CPU")
# parser.add_argument("--decoder_model_name", default='CE2T', type=str, help="CE2T ConnectE ETE")
# parser.add_argument("--margin", default=2.0, type=float, help="ConnectE ETE’s margine ")
# parser.add_argument('--embsize_entity', default=100, help='Entity Embedding size (default: 200)')
# parser.add_argument('--embsize_relation', default=100, help='Entity Embedding size (default: 200)')
# parser.add_argument('--embsize_entity_type', default=200, help='Entity Type Embedding size (default: 100)')
# parser.add_argument('--num_layers', type=int, default=2, help='Number of FRGAT layers')
# parser.add_argument('--nb_heads', type=int, default=2, help='Number of head attentions.')
# parser.add_argument('--hidden_embedding_size', type=int, default=300, help='Number of hidden units.')
# parser.add_argument('--output_embedding_size', type=int, default=600, help='Number of input units.')
# parser.add_argument("--alpha", "--alpha", type=float, default=0.2, help="LeakyRelu alphs for FRGAT layer")
# parser.add_argument('--frgat_drop', default=0.3, type=float, help='FRGAT dropout')
# parser.add_argument('--frgat_output_dropout', default=0.2, type=float, help='FRGAT output dropout')
# parser.add_argument('--frgat_initial_dropout', default=0.0, type=float, help='FRGAT initial dropout')
# parser.add_argument('--frgat_computing_model', default='DisMult', type=str,
#                     help='Attention computing model:TransE TransH TransD DisMult RotatE QuatE dot')
# parser.add_argument('--frgat_composition_operator', default='sub', type=str, help='sub mult corr void')
# parser.add_argument('--indir', type=str, default='data/YAGO/',
#                     help='Input dir of train, test and valid data: data/FB15K/ data/YAGO/ data/FB15K-237 data/JF17K')
# parser.add_argument('--outdir', type=str, default='output/YAGO/', help='Output dir of model')


#CE2T FB15K
# parser.add_argument('--epochs', default=500, help='Number of epochs (default: 200)')
# parser.add_argument('--batchsize', type=int, default=128, help='Batch size (default: 128)')
# parser.add_argument('--num_filters', type=int, default=9, help='number of filters CNN')
# parser.add_argument('--filt_h', type=int, default=1, help='filt_h of  CNN')
# parser.add_argument('--filt_w', type=int, default=2, help='filt_w of CNN')
# parser.add_argument('--conv_stride', type=int, default=2, help='stride of CNN')
# parser.add_argument('--h', type=int, default=1, help='h')
# parser.add_argument('--w', type=int, default=600, help='w')
# parser.add_argument('--pool_h', type=int, default=1, help='pool_h')
# parser.add_argument('--pool_w', type=int, default=2, help='pool_w')
# parser.add_argument('--pool_stride', type=int, default=2, help='pool_w')
# parser.add_argument('--embsize_entity', default=600, help='Entity Embedding size (default: 200)')
# parser.add_argument('--embsize_entity_type', default=200, help='Entity Type Embedding size (default: 100)')
# parser.add_argument('--learningrate', default=0.0001, help='Learning rate (default: 0.00005)')
# parser.add_argument("--droupt_input", default=0.0, type=float, help="droupt regularization item 0.2")
# parser.add_argument("--droupt_feature", default=0.0, type=float, help="droupt regularization item 0.2")
# parser.add_argument("--droupt_output", default=0.4, type=float, help="droupt regularization item 0.2")
# parser.add_argument("--label_smoothing", default=0.1, type=float, help="label smoothing")
# parser.add_argument("--CUDA", default=True, type=bool, help="GPU")
# parser.add_argument("--model_name", default='CE2T', type=str, help="CE2T ConnectE ETE")
# parser.add_argument("--margin", default=1.0, type=float, help="ConnectE ETE’s margine ")
# parser.add_argument('--dataset', type=str, default="FB15k", nargs="?",
#                     help='Which dataset to use: FB15k, YAGO')
# parser.add_argument('--indir', type=str, default='data/FB15k/', help='Input dir of train, test and valid data')
# parser.add_argument('--outdir', type=str, default='output/FB15k/', help='Output dir of model')
# parser.add_argument('--load', default='True',help='If true, it loads a saved model in outdir and train or evaluate it (default: False)')

#CE2T YAGO
# parser.add_argument('--epochs', default=500, help='Number of epochs (default: 200)')
# parser.add_argument('--batchsize', type=int, default=128, help='Batch size (default: 128)')
# parser.add_argument('--num_filters', type=int, default=9, help='number of filters CNN')
# parser.add_argument('--filt_h', type=int, default=1, help='filt_h of  CNN')
# parser.add_argument('--filt_w', type=int, default=2, help='filt_w of CNN')
# parser.add_argument('--conv_stride', type=int, default=2, help='stride of CNN')
# parser.add_argument('--h', type=int, default=1, help='h')
# parser.add_argument('--w', type=int, default=400, help='w')
# parser.add_argument('--pool_h', type=int, default=1, help='pool_h')
# parser.add_argument('--pool_w', type=int, default=2, help='pool_w')
# parser.add_argument('--pool_stride', type=int, default=2, help='pool_w')
# parser.add_argument('--embsize_entity', default=400, help='Entity Embedding size (default: 200)')
# parser.add_argument('--embsize_entity_type', default=200, help='Entity Type Embedding size (default: 100)')
# parser.add_argument('--learningrate', default=0.0001, help='Learning rate (default: 0.00005)')
# parser.add_argument("--droupt_input", default=0.0, type=float, help="droupt regularization item 0.2")
# parser.add_argument("--droupt_feature", default=0.0, type=float, help="droupt regularization item 0.2")
# parser.add_argument("--droupt_output", default=0.4, type=float, help="droupt regularization item 0.2")
# parser.add_argument("--label_smoothing", default=0.1, type=float, help="label smoothing")
# parser.add_argument("--CUDA", default=True, type=bool, help="GPU")
# parser.add_argument("--model_name", default='CE2T', type=str, help="CE2T ConnectE ETE")
# parser.add_argument("--margin", default=1.0, type=float, help="ConnectE ETE’s margine ")
# parser.add_argument('--dataset', type=str, default="FB15k", nargs="?",
#                     help='Which dataset to use: FB15k, YAGO')
# parser.add_argument('--indir', type=str, default='data/FB15k/', help='Input dir of train, test and valid data')
# parser.add_argument('--outdir', type=str, default='output/FB15k/', help='Output dir of model')
# parser.add_argument('--load', default='True',help='If true, it loads a saved model in outdir and train or evaluate it (default: False)')